# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from rgw.auth.v1 import auth_pb2 as rgw_dot_auth_dot_v1_dot_auth__pb2


class AuthServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Auth = channel.unary_unary(
                '/rgw.auth.v1.AuthService/Auth',
                request_serializer=rgw_dot_auth_dot_v1_dot_auth__pb2.AuthRequest.SerializeToString,
                response_deserializer=rgw_dot_auth_dot_v1_dot_auth__pb2.AuthResponse.FromString,
                )
        self.Status = channel.unary_unary(
                '/rgw.auth.v1.AuthService/Status',
                request_serializer=rgw_dot_auth_dot_v1_dot_auth__pb2.StatusRequest.SerializeToString,
                response_deserializer=rgw_dot_auth_dot_v1_dot_auth__pb2.StatusResponse.FromString,
                )


class AuthServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Auth(self, request, context):
        """Given an S3 request, attempt to authenticate a user id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Simple ping-like service, useful for service liveness checks.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Auth': grpc.unary_unary_rpc_method_handler(
                    servicer.Auth,
                    request_deserializer=rgw_dot_auth_dot_v1_dot_auth__pb2.AuthRequest.FromString,
                    response_serializer=rgw_dot_auth_dot_v1_dot_auth__pb2.AuthResponse.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=rgw_dot_auth_dot_v1_dot_auth__pb2.StatusRequest.FromString,
                    response_serializer=rgw_dot_auth_dot_v1_dot_auth__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rgw.auth.v1.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Auth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rgw.auth.v1.AuthService/Auth',
            rgw_dot_auth_dot_v1_dot_auth__pb2.AuthRequest.SerializeToString,
            rgw_dot_auth_dot_v1_dot_auth__pb2.AuthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rgw.auth.v1.AuthService/Status',
            rgw_dot_auth_dot_v1_dot_auth__pb2.StatusRequest.SerializeToString,
            rgw_dot_auth_dot_v1_dot_auth__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
